//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManicStreetCoder.AzureDashform.Windows.UI.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManicStreetCoder.AzureDashform.Windows.UI.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;properties&quot;: {
        ///        &quot;lenses&quot;: {
        ///            &quot;0&quot;: {
        ///                &quot;order&quot;: 0,
        ///                &quot;parts&quot;: {
        ///                    &quot;0&quot;: {
        ///                        &quot;position&quot;: {
        ///                            &quot;x&quot;: 0,
        ///                            &quot;y&quot;: 0,
        ///                            &quot;rowSpan&quot;: 4,
        ///                            &quot;colSpan&quot;: 6
        ///                        },
        ///                        &quot;metadata&quot;: {
        ///                            &quot;inputs&quot;: [
        ///                                {
        ///                      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoldenMasterInputTemplate1 {
            get {
                return ResourceManager.GetString("GoldenMasterInputTemplate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;properties&quot;: {
        ///        &quot;lenses&quot;: {
        ///            &quot;0&quot;: {
        ///                &quot;order&quot;: 0,
        ///                &quot;parts&quot;: {
        ///                    &quot;0&quot;: {
        ///                        &quot;position&quot;: {
        ///                            &quot;x&quot;: 0,
        ///                            &quot;y&quot;: 0,
        ///                            &quot;rowSpan&quot;: 4,
        ///                            &quot;colSpan&quot;: 6
        ///                        },
        ///                        &quot;metadata&quot;: {
        ///                            &quot;inputs&quot;: [
        ///                                {
        ///                      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoldenMasterInputTemplate2 {
            get {
                return ResourceManager.GetString("GoldenMasterInputTemplate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;$schema&quot;: &quot;https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#&quot;,
        ///	&quot;contentVersion&quot;: &quot;1.0.0.0&quot;,
        ///	&quot;parameters&quot;: {
        ///		&quot;appInsightsName&quot;: {
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;dashboardName&quot;: {
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;dashboardDisplayName&quot;: {
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;nameOfResourceGroup&quot;: {
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;subscriptionId&quot;: {
        ///			&quot;type&quot;: &quot;string&quot;
        ///		}
        ///	},
        ///	&quot;variables&quot;: {},
        ///	&quot;resources&quot;: [
        ///		{
        ///			&quot;properties&quot;: {
        ///				&quot;lenses&quot;: {
        ///					&quot;0&quot;: {
        ///						&quot;o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoldenMasterOutputTemplate1 {
            get {
                return ResourceManager.GetString("GoldenMasterOutputTemplate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;$schema&quot;: &quot;https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#&quot;,
        ///	&quot;contentVersion&quot;: &quot;1.0.0.0&quot;,
        ///	&quot;parameters&quot;: {
        ///		&quot;appInsightsName&quot;: {
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;dashboardName&quot;: {
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;dashboardDisplayName&quot;: {
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;nameOfResourceGroup&quot;: {
        ///			&quot;type&quot;: &quot;string&quot;
        ///		},
        ///		&quot;subscriptionId&quot;: {
        ///			&quot;type&quot;: &quot;string&quot;
        ///		}
        ///	},
        ///	&quot;variables&quot;: {},
        ///	&quot;resources&quot;: [
        ///		{
        ///			&quot;properties&quot;: {
        ///				&quot;lenses&quot;: {
        ///					&quot;0&quot;: {
        ///						&quot;o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoldenMasterOutputTemplate2 {
            get {
                return ResourceManager.GetString("GoldenMasterOutputTemplate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;$schema&quot;: &quot;https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#&quot;,
        ///	&quot;contentVersion&quot;: &quot;1.0.0.0&quot;,
        ///	&quot;parameters&quot;: {
        ///		&quot;nameOfResourceGroup&quot;: {
        ///			&quot;value&quot;: &quot;#{ResourceGroup.Name}&quot;
        ///		},
        ///		&quot;subscriptionId&quot;: {
        ///			&quot;value&quot;: &quot;#{AzureSubscriptionId}&quot;
        ///		},
        ///		&quot;appInsightsName&quot;: {
        ///			&quot;value&quot;: &quot;#{ApplicationInsights.Name}&quot;
        ///		},
        ///		&quot;dashboardName&quot;: {
        ///			&quot;value&quot;: &quot;#{Dashboard.Name}&quot;
        ///		},
        ///		&quot;dashboardDisplayName&quot;: {
        ///			&quot;value&quot;: &quot;#{Dashboard.DisplayName}&quot;
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string GoldenMasterParameters {
            get {
                return ResourceManager.GetString("GoldenMasterParameters", resourceCulture);
            }
        }
    }
}
